name: server

on:
  push:
    branches:
      - master

jobs:
  deploy-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: SetEnv
        run: |
          echo ${{ TENCENT_USERNAME }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 35iter/blog-strapi:latest
      - name: Save Image
        run: |
          docker save 35iter/blog-strapi:latest | gzip > blog-strapi.tar.gz
      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ TENCENT_HOST }}
          username: ${{ TENCENT_USERNAME }}
          password: ${{ TENCENT_PASSWORD }}
          port: 22
          source: blog-strapi.tar.gz
          target: /home/ubuntu
      - name: Update Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ TENCENT_HOST }}
          username: ${{ TENCENT_USERNAME }}
          password: ${{ TENCENT_PASSWORD }}
          port: 22
          script: |
            ./deploy-blog-strapi.sh
